# Generated by Django 5.1 on 2024-09-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0004_anonymousparticipant_approval_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participants',
            name='user',
            field=models.CharField(max_length=255),
        ),
    ]
