# Generated by Django 5.1 on 2024-09-11 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0005_alter_participants_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participants',
            old_name='user',
            new_name='name',
        ),
    ]
