# Generated by Django 5.1 on 2024-09-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loom', '0007_rename_content_message_message_alter_message_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='anonymous_user',
        ),
        migrations.AlterField(
            model_name='anonymousparticipant',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='message',
            name='user',
            field=models.CharField(default='Participants', max_length=255),
        ),
    ]
