# Generated by Django 5.1 on 2024-08-26 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0006_todomodel_pined'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='todomodel',
            name='tags',
            field=models.ManyToManyField(related_name='todos', to='back.tag'),
        ),
    ]
