# Generated by Django 5.1 on 2024-08-30 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0007_tag_todomodel_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default=True, max_length=100),
        ),
    ]
