# Generated by Django 5.1 on 2024-09-01 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('back', '0008_user_first_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='verifyOtp',
            field=models.BooleanField(default=False),
        ),
    ]
